
*** 万历十五年(无关紧要的 1587 年, 衰弱的大明王朝)

一般史家认为的明朝灭亡之起点, 有如万历十年(1582)张居正去世;
而后神宗皇帝朱翊钧开始新政, 因为立太子之事与文官发生了长达十余年的争执, 从 1586 年开始, 其开始连续不上朝长达三十年;
万历二十年(1592) 长达 6 年的援朝鲜战争; 及万历四十六年(1619)的萨尔浒之战.
与这些年份相比, 万历十五年(1587)虽然有海瑞、戚继光的去世, 但终究只是无足轻重的一年.

黄仁宇先生 提出不同的看法, 万历十五年这平常的一年看似是天下盛平, 无重大动荡, 实际上可能却是明朝发展至尽头而步向灭亡的一年.

黄仁宇引用典籍, 特别是《神宗实录》, 就此年中发生的立储之争和一连串使万历帝感到大为不快的问题作分析, 研究发生在万历帝身上的变化.
黄仁宇指出, 虽然最后万历帝在种种问题上妥协, 但他由此怠政三十三年, 可能是他对抗无效之后, 对文官集团的一种报复方式.
由此可以理解, 明朝的皇帝表面上是有至高无上的绝对权力, 但终归也要受到传统文化和文官集团的掣肘.

另外书中还提到 海瑞、戚继光、李贽 等人, 也是受到传统文化的掣肘, 而得不到有意义的发展.

对海瑞, 黄仁宇形容 “他虽然被人仰慕, 但没有人按照他的榜样办事, 他的一生体现了一个有教养的读书人服务于公众而牺牲自我的精神, 但这种精神的实际作用却至为微薄.”

对戚继光, 黄仁宇评 “戚继光的求实精神, 表现于使革新不与传统距离过远.”

而对李贽, 黄仁宇也评说李贽不过是反映明朝在儒家伦理文化趋于僵化下, 思想界的苦闷和困局.


注重于对这 6 个历史人物(万历、张居正、申时行)的批评, 本书相当于一纸诉状. 帝国的官僚们一意保持传统和稳定, 从而丧失了主动性, 甚至不惜行事不公. 简而言之, 成功操守了中国: 一个高度程式化的社会过快, 个人角色被彻底束缚住了.(278)

-----

戚继光是一个天才的将军, 在这无关紧要的万历十五年底去世. 他使数量巨大但实际不堪一击的军队恢复了, 独立编撰了军事操典, 创制了新的战斗队形和战斗, 享有因抗击沿海倭寇和北方蒙古人而令人欢欣鼓舞的成功. 然而, 随着他的保护人首辅张居正的去世及其身后的失宠, 这位伟大的勇士被降职了, 最终受到责难并被解职, 在贫困交加中凄凉辞世. 军官们几乎是一个完全世袭的阶层, 被认为仅具打斗之长. 他们得不到文官的信任, 而后者则专注于克己与中庸之道. 任何肇基于帝国官僚政治之外的权力必须得到控制, 而 “随着戚继光的去世, 我们的帝国失去了将它的军队施予最低程度的现代化以图在新时代里生存的最后一次机会.”

: 他和谭纶、张居正的关系如此密切, 张居正死后, 廷臣提醒万历: 戚继光是伏在宫门之外的一头猛兽, 
: 只听张居正的操纵, 别人无法节制. 这也正是控诉张居正意图谋逆的理由: 张居正和戚继光没有造反的证据, 却有造反的能力.
: 他在贫病交迫中死去. 在少数几个没有遗弃他的朋友之中, 有一位就是为他写墓志铭的汪道昆. 当他写到 "口鸡三号, 将星殒矣", 
: 显然有无限凄怆的三角. 汪道昆自然不会知道, 当他润笔作书的时候, 西班牙的舰队, 已整备出征英国. 
: 而这阳历 1588 年 1 月 17 号清晨, 将星陨落之际, 我们古老的帝国业已失去重整军备的最好良机.
: 三十年后, 本朝的官兵和努尔哈赤的部队交锋, 缺乏戚南塘将军苦心孤诣拟订的战术和强调的组织纪律, 
: 结果是众不敌寡. 兹后八旗军作为一股新生力量崛起于白山黑水之间, 其取本朝而代之, 也只是迟早的问题了.(180)

-----

1587 年去世的还有著名的海瑞. 他是一个极度严正的文职官员, 敢于在一封公开的奏疏里批评嘉靖皇帝 "虚荣、残忍、自私、多疑和愚蠢".

: 海瑞从政二十多年的生活, 充满了各种各样的纠纷. 他的信条和个性使他既被人尊重, 也被人遗弃. 
: 也就是说, 他虽然这被人仰慕, 但没有人按照他的榜样行事. 
: 他的一生体现了一个有教养的读书人服务于公众而牺牲自我的精神, 但这种精神的实际作用却至为微薄.
: 他可以和舞台上的英雄人物一样, 在情绪上激动大多数的观众;
: 但是, 当人们评论他的政治措施, 却不仅会意见分歧, 而且分歧的程度极大.
: 在各种争执中最容易找出的一个共通的结论, 就是他的所作所为无法被接受为全体文官们办事的准则.(124)
: 
: 海瑞既是忠臣, 又是孝子. 他四岁丧父, 孀居的母亲忍受着极大的困难把他教养成人.
: 她是他的抚养者, 也是他的启蒙者. 在海瑞没有投师就读以前, 她就对他口授经书.
: 所以, 历史学家们认为海瑞的刚毅正直, 其中就有着他母亲的影子.
: 然而, 同样为人承认的是, 海太夫人又是造成这个家庭中不幸事故的重要因素.
: 当海瑞离开南直隶的时候, 她已经度过了八十寿辰.
: 而出人意外的是, 海瑞的上司只是呈请皇帝给予四品夫人的头衔, 而始终没有答应给她以另外一种应得的荣誉, 即旌表为节妇.
: 是不是因为她的个性过强, 以致使他的儿子两次出妻? 又是不是她需要对 1569 年的家庭悲剧承担责任?
: 由于海太夫人而引起的家庭纠纷, 不仅已经成为政敌所攻讦的口实, 也已为时论所不满.
: 海瑞可以极容易地从伦常纲纪中找出为他母亲和自己辩护的根据, 却不会丝毫增加他家庭的和睦.(144)

在万历十五年丁亥的岁暮, 海瑞的死讯传出, 无疑使北京的朝廷大大地松了口气. 现在, 没有人必须为罢免一个大众心目中的英雄而承担责任了. 在同僚和皇帝的眼中, 海瑞无聊可笑, 又不合时宜(279)

-----

第三位叛逆者是想冲破当时社会制度却无法找到出路的哲学家李贽. 他对神圣的儒家经典发表了大量的惊世骇俗之论, 因其中包含有平等思想的迹象而受到当今中国统治者的喜爱. 不过, 实际上李贽并没有完全摆脱精英分子和儒家的信条, 正是这些信条养育了他. 对黄先生来说, 李贽的著作起码构成了 "一份珍贵的记录, 使我们得以了解这个时代所特有的知识界的挫败. 没有这些著作, 我们将可能无从探测这挫败的深度"

-----

张居正和申时行这两位首辅的职业生涯提供了另一种挫败的实例. 我们的帝国因其中央集权和过度膨胀而运转不灵, 但他们企图管理帝国的一切事务. 他们的这一企图受制于圣贤教育的成规, 因之他们最基本的任务是 "使皇帝的官员们尽量按照古代圣贤的教导行事"

: 管理我们这个庞大帝国的秘诀是不能依靠法律或权力去管制和惩罚, 
: 而是劝导人们, 青年人要尊敬老年人, 女人要服从男人, 文盲要追随读书识字的人.
: 在这方面, 官员们的表率作用就极其重要.(280)

(142)制度的原始性和简单性, 在大众之中造成了很多不幸的后果. 官府衙门除了对刑事案件必须作出断然处置外, 很少很注意到对日常生活中的种种纠纷维持公允. 乡村中的士绅耆老, 虽然被赋予了这方面的仲裁权, 然而他们更关心的是自己的社会地位和社交活动, 对这些琐碎乏味的纠纷大多缺乏热情和耐心. 至于开发民智这一类概念, 在他们心目中更不占有任何地位. 在我们这个古老的礼义之邦里, 绝大多数的农民实际上早就列为顽民愚氓, 不在文化教养之内, 即使在模范官员海瑞的笔下, 这些张民也似乎只是一群动物, 既浑浑噩噩, 又狠毒狡诈, 易于冲动. 日常生活中为小事而发生口角已属司空见惯, 打架斗殴以致死伤也时有发生.

-----

最为引人注意的是神宗皇帝本人, 他即位时不足九岁, 到 1587 年只才只是一位 24 岁的年轻人, 但他注定是明朝历史上在位时间最长的一位皇帝. 万历是一个早熟而听话的孩子, 不仅要学习书法、历史和经学, 还欣然履行皇帝所需承担的各种礼仪职责. 除了藉田、祭祀天地祖宗和颁历这样的周期性仪式外, 每天的早朝也要求皇帝出席. 这种日复一日的早朝仪式极端刻板, 必须在拂晓前举行, 此前就已成为皇帝难以忍受的负担. 包括万历冷漠的父亲即隆庆皇帝在内, 万历之前有好几位皇帝都荒于早朝. 等到万历成年, 他也发现即使早朝时间缩短, 还是令人难以忍受.

万历十四岁结婚, 十八岁时王恭妃给他生了第一个孩子. 这时, 他爱上了另一个妃子: 只有十四岁却很聪明的郑氏. 皇帝希望郑氏的儿子而不是长子来继承皇位, 为此跟他的臣僚们疏远了数十年. 他拒绝上朝会见大臣, 拒绝任命官员, 而大明帝国因之越来越滑向混乱无序的深渊.

明朝的特性在于 "依靠意识形态作为统治手段, 意识形态充斥了帝国的各个方面, 无论从强度还是从广度来说, 都是空前未有", 跟蒙古人一样, 取代明朝的满洲人也是从北方来的入侵者. 他们能强迫汉人剃发结辫, 却不能说服汉人禁止妇女缠足, 反面被汉人同化了. 在经过了漫长而耻辱的衰落期之后, 1912 年这一王朝也终告消亡.(283)

-----

《万历十五年》指出道德非万能, 不能代替技术, 尤不可代替法律, 但是从没有说道德可以全部不要, 只是说道德的观点应当远大. 凡能先用法律及技术解决的问题, 不要先就扯上一个道德问题. 道德是一切意义的根源, 不能分割, 也不便妥协, 如果道德上的争执持久不能解决, 双方的距离越来越元, 则迟早必导致战争.(250)
